sonar.projectKey=red-star25_mernspace-c-auth-service
sonar.organization=red-star25
sonar.projectName=mernspace-c-auth-service
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/migrations/**
sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.scm.exclusions.disabled=true